// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFfllNWmxhqAcjIC6e2Tv1U-gumDQ3arw',
    appId: '1:627740867098:web:77473ff6f9cef331f62fa3',
    messagingSenderId: '627740867098',
    projectId: 'exploreera-4e9ca',
    authDomain: 'exploreera-4e9ca.firebaseapp.com',
    storageBucket: 'exploreera-4e9ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN1F2eb2v26dV6dRxPWluKih95Gvw_v2o',
    appId: '1:627740867098:android:01b2fa6119244aadf62fa3',
    messagingSenderId: '627740867098',
    projectId: 'exploreera-4e9ca',
    storageBucket: 'exploreera-4e9ca.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFfllNWmxhqAcjIC6e2Tv1U-gumDQ3arw',
    appId: '1:627740867098:web:19b29ce84ffab73cf62fa3',
    messagingSenderId: '627740867098',
    projectId: 'exploreera-4e9ca',
    authDomain: 'exploreera-4e9ca.firebaseapp.com',
    storageBucket: 'exploreera-4e9ca.appspot.com',
  );

}